name: Build Chrome Extension
#Tsemach
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Create extension directory
        run: |
          mkdir extension
          cp src/manifest.json extension/
          cp src/background.js extension/
          cp src/popup.html extension/
          cp src/popup.js extension/
          cp src/styles.css extension/
          cp src/icon*.png extension/
          cp src/icon*.svg extension/

      - name: Zip extension
        run: zip -r mockitextension.zip extension

      - name: Upload artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: mockitextension
          path: mockitextension.zip

